---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark #light/dark

identity_validation:
  reset_password:
    jwt_secret: '{{ env "JWT_SECRET" }}'

server:
  address: "tcp://0.0.0.0:9091/"
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
  endpoints:  
    enable_pprof: false
    enable_expvars: false
  buffers:
    read: 4096
    write: 4096

log:
  level: debug

totp:
  issuer: '{{ env "SEARXNG_HOSTNAME" }}' #your authelia top-level domain
  period: 30
  skew: 1

authentication_backend:
  password_reset: 
    disable: true
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    - domain: 'auth.{{ env "SEARXNG_HOSTNAME" }}' #This should be your authentication URL
      policy: bypass #Do not ask for credentials
    - domain: '{{ env "SEARXNG_HOSTNAME" }}' #example domain to protect
      policy: one_factor

session:
  name: authelia_session
  secret: '{{ env "SESSION_SECRET" }}'
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  cookies:
    - domain: '{{ env "SEARXNG_HOSTNAME" }}'
      authelia_url: 'https://auth.{{ env "SEARXNG_HOSTNAME" }}'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '30d'

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you wanted, but we're going to use this one.
  encryption_key: '{{ env "ENCRYPTION_KEY" }}'

notifier:
  filesystem:
    filename: /config/notification.txt
